### ISSUE TITLE
Unexpected behaviour with control flag 25, value 0

### ISSUE THREAD

**Issue by tom-peatman** [johnrsibert/tagest#2]
Hi John,

I ran a model with control flag 25 set to 0, and supplied fleet specific catchabilities in the run.par file. However, the q parameters quoted in the -p00x.par and -p00x.rep files in the functional run directory are all set to 0.25 (not my supplied q's).

Based on the model fit, it seems likely that the correct q's were used in the model, and that the parameter values for q in -p00x.par and -p00x.rep files are incorrect.

Cheers,
Tom

**Comment by johnrsibert** [comment]
Hi Tom,
I'm unable to reproduce your error (although there is a problem with the .rep file; see below). 

Here is what I did working in the `<example/grid16/grid16skj folder>`:
1. Copied grid16.p002 to grid16.par (not strictly necessary, but it is faster to start with a converged fit).
2. Edit grid16.par: set flag 25 to zero; set all catchabilities to 0.05,
3. Run tagest
4. Verify input is correct by examining gri16.ppp. (This file is an "echo" of the input.) Indeed q=0.05 for all fleets.
5. Examine new estimates in grid16.p003. q=0.05 for all fleets. But note that some D estimates are at their bounds, and no grid16-p003.std file was not produced indicating that no true minimum was found.
6. grid16-p003.rep does indeed contain incorrect values. The reason is unknown, but the REPORT_SECTION of tagest.tpl has not seen much love recently.  In any case, **the definitive results from the most recent tagest run will always be found in the highest numbered .pxxx file**

**Comment by tom-peatman** [comment]
Hi John,

Thanks for looking at that. Interesting that the error I encountered was not reproduced. To confirm, I checked the .pxxx file for the run in question, and the correct catchabilities were used in the model fit. 

I'll make sure I take model parameters directly from the .pxxx file.

**Comment by johnrsibert** [comment]
Hi Tom,
Actually, I think the -pxxx.par files do indeed contain the incorrect values. I was able to reproduce this error.

The documentation does not convey much information about output files (but a lot about input files). This is an issue that should be addressed.

I think I fixed the issue with the .rep file, and will push the changes soon.

John
